module FractionIDL
{
    struct FractionRep
    {
        long long numerator;
        long long denominator;
    };

    interface Fraction
    {
        FractionRep add(in FractionRep lhs, in FractionRep rhs);
    };
};