package FractionIDL;

/**
* FractionIDL/FractionRepHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Mike/IdeaProjects/FractionIDL/idl/Fraction.idl
* Saturday, October 21, 2017 12:47:58 PM EDT
*/

public final class FractionRepHolder implements org.omg.CORBA.portable.Streamable
{
  public FractionIDL.FractionRep value = null;

  public FractionRepHolder ()
  {
  }

  public FractionRepHolder (FractionIDL.FractionRep initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FractionIDL.FractionRepHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FractionIDL.FractionRepHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FractionIDL.FractionRepHelper.type ();
  }

}
