package FractionIDL;


/**
* FractionIDL/FractionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Mike/IdeaProjects/FractionIDL/idl/Fraction.idl
* Saturday, October 21, 2017 12:47:58 PM EDT
*/

public interface FractionOperations 
{
  FractionIDL.FractionRep add (FractionIDL.FractionRep lhs, FractionIDL.FractionRep rhs);
} // interface FractionOperations
