package FractionIDL;


/**
* FractionIDL/FractionRepHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Mike/IdeaProjects/FractionIDL/idl/Fraction.idl
* Saturday, October 21, 2017 12:47:58 PM EDT
*/

abstract public class FractionRepHelper
{
  private static String  _id = "IDL:FractionIDL/FractionRep:1.0";

  public static void insert (org.omg.CORBA.Any a, FractionIDL.FractionRep that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FractionIDL.FractionRep extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_longlong);
          _members0[0] = new org.omg.CORBA.StructMember (
            "numerator",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_longlong);
          _members0[1] = new org.omg.CORBA.StructMember (
            "denominator",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (FractionIDL.FractionRepHelper.id (), "FractionRep", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FractionIDL.FractionRep read (org.omg.CORBA.portable.InputStream istream)
  {
    FractionIDL.FractionRep value = new FractionIDL.FractionRep ();
    value.numerator = istream.read_longlong ();
    value.denominator = istream.read_longlong ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FractionIDL.FractionRep value)
  {
    ostream.write_longlong (value.numerator);
    ostream.write_longlong (value.denominator);
  }

}
