package FractionIDL;


/**
* FractionIDL/FractionPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Mike/IdeaProjects/FractionIDL/idl/Fraction.idl
* Saturday, October 21, 2017 12:47:58 PM EDT
*/

public abstract class FractionPOA extends org.omg.PortableServer.Servant
 implements FractionIDL.FractionOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("add", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // FractionIDL/Fraction/add
       {
         FractionIDL.FractionRep lhs = FractionIDL.FractionRepHelper.read (in);
         FractionIDL.FractionRep rhs = FractionIDL.FractionRepHelper.read (in);
         FractionIDL.FractionRep $result = null;
         $result = this.add (lhs, rhs);
         out = $rh.createReply();
         FractionIDL.FractionRepHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FractionIDL/Fraction:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Fraction _this() 
  {
    return FractionHelper.narrow(
    super._this_object());
  }

  public Fraction _this(org.omg.CORBA.ORB orb) 
  {
    return FractionHelper.narrow(
    super._this_object(orb));
  }


} // class FractionPOA
