package FractionIDL;

/**
* FractionIDL/FractionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Mike/IdeaProjects/FractionIDL/idl/Fraction.idl
* Saturday, October 21, 2017 12:47:58 PM EDT
*/

public final class FractionHolder implements org.omg.CORBA.portable.Streamable
{
  public FractionIDL.Fraction value = null;

  public FractionHolder ()
  {
  }

  public FractionHolder (FractionIDL.Fraction initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FractionIDL.FractionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FractionIDL.FractionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FractionIDL.FractionHelper.type ();
  }

}
